### ISSUE TITLE
Buying

### ISSUE THREAD

**Issue by DJBlackStore99** [TheSpartaPT/vrp_pets#1]
Boas , desde ja uma boa continuacao de trabalho, so para confirmar.
Tive a testar o script mas ele simplesmente nao compra o animal.
ja adicionei a linha na base de dados, mas n funciona, tenho de fazer algo mais? 
ou ainda n testas-te o script?

Obrigado desde ja.

**Comment by TheSpartaPT** [comment]
vrp ou vrpex ? eu fiz para vrp não para vrpex ...
