### ISSUE TITLE
error

### ISSUE THREAD

**Issue by johnwickbr** [TheSpartaPT/vrp_pets#3]
[ERROR] [MySQL] An error happens on MySQL for query "UPDATE vrp_users SET pet = @pet WHERE id = @id {@id=1;@pet=husky}": Unable to connect to any of the specified MySQL hosts.

**Comment by TheSpartaPT** [comment]
> Unable to connect to any of the specified MySQL hosts.
 
This is your problem, you need to follow the install instructions, and get MySQL-Async working. Since this is not an issue with my script I'm closing this
