### ISSUE TITLE
O VRP não está funcionando para mim.

### ISSUE THREAD

**Issue by gu-amorim** [TheSpartaPT/vrp_pets#5]
Olá, tudo bem? 
Eu baixei o vrp_pets, adicionei ele nos meus resources, e adicionei 'start vrp_pets' no código da base. Mas assim que eu entro no server e vou ao local do petshop, não há nada, nenhum blip.

Será que você pode me ajudar?

**Comment by TheSpartaPT** [comment]
o script ta feito para a versão antiga do vrp, se queres meter a funcionar na nova vais ter que ser tu a alterar.
